import json
import os
from datetime import datetime
import glob

def generate_medical_summary():
    # Path to results directory
    results_dir = r"C:\Users\ARUN\Downloads\research engineer\multimodal\images_010\analysis_results"
    
    # Get all JSON files
    json_files = glob.glob(os.path.join(results_dir, 'batch_*.json'))
    
    # Create output directory for reports if it doesn't exist
    reports_dir = os.path.join(results_dir, 'comprehensive_reports')
    os.makedirs(reports_dir, exist_ok=True)
    
    # Combine all results
    all_results = []
    for json_file in json_files:
        with open(json_file, 'r') as f:
            batch_results = json.load(f)
            all_results.extend(batch_results)
    
    # Generate timestamp for the report
    timestamp = datetime.now().strftime("%B %d, %Y %H:%M:%S")
    
    # Create the comprehensive report
    report_path = os.path.join(reports_dir, f'Medical_Report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.txt')
    
    with open(report_path, 'w') as report:
        # Write header
        report.write(f"""
{'='*80}
                    RADIOLOGICAL CONSULTATION REPORT
                    Advanced AI-Assisted Analysis
{'='*80}

Date of Report: {timestamp}
Analyzing Physician: Dr. AI Assistant
Department: Radiology
Institution: AI Research Medical Center

DISCLAIMER: 
This report is generated using artificial intelligence and should be used only as a 
supporting tool. All findings must be verified by a licensed healthcare professional.

{'='*80}

SUMMARY OF ANALYSES
Total Images Processed: {len(all_results)}

{'='*80}

DETAILED FINDINGS:
""")
        
        # Process each case
        for i, result in enumerate(all_results, 1):
            report.write(f"""
CASE {i}
{'~'*40}
Image ID: {result['image_name']}
Date Processed: {result['processed_at']}

RADIOLOGICAL OBSERVATIONS:
------------------------""")
            
            # Write findings
            for obj in result['findings']['objects']:
                report.write(f"\n• {obj}")
            for feature in result['findings']['features']:
                report.write(f"\n• {feature}")
            
            report.write(f"""

MEDICAL INTERPRETATION:
---------------------
{result['interpretation']}

RECOMMENDATIONS:
--------------
1. Clinical correlation is advised
2. Follow-up imaging may be necessary based on clinical course
3. Consider additional views if specific concerns arise

{'='*80}
""")
        
        # Write footer
        report.write(f"""
REPORT AUTHENTICATION
--------------------
Generated by: Advanced AI Diagnostic System
Date: {timestamp}
Report ID: {datetime.now().strftime("%Y%m%d%H%M%S")}

NOTE: This report represents an AI-assisted analysis and should be reviewed by a 
qualified healthcare professional. The findings and interpretations are meant to 
support, not replace, clinical judgment.

{'='*80}
""")
    
    return report_path

if __name__ == "__main__":
    print("Generating comprehensive medical report...")
    report_path = generate_medical_summary()
    print(f"\nReport generated successfully!")
    print(f"Location: {report_path}")
    
    # Preview the report
    print("\nPreview of the report:")
    print("-" * 40)
    with open(report_path, 'r') as f:
        print(f.read().strip())